### PR TITLE
SapMachine11 #530: Enable ShowCodeDetailsInExceptionMessages per defaul…

### LINKED ISSUE #530: Enable ShowCodeDetailsInExceptionMessages per default in SapMachine (JDK-8233014)
This change is planned for OpenJDK 15 or later. 
We want to enable the feature in SapMachine right away.

https://bugs.openjdk.java.net/browse/JDK-8233014

### PR DESCRIPTION
**Pull request by GoeLin**
…t in SapMachine (JDK-8233014)

(cherry picked from commit e6a354d8f1906f50caf71febdcdae9b17f440d6e)

fixes #530

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by GoeLin** [comment]
Test compiler/aot/calls/fromAot/AotInvokeSpecial2AotTest.java was failing in the linux x86_64 build. I can not reproduce this locally, nor did the rebuild reproduce this. Also, the test seems not to depend on a NPE message.

**Pull request merged**
