### PR TITLE
SapMachine #320: Update SapMachine branding

### LINKED ISSUE #320: Update SapMachine branding
There are several places in OpenJDK where vendors can add their branding information. This gets effective in e.g. System properties, executable meta information, icons etc. SapMachine should make use of this.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #320

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Hi @reshnm 

> Hi @RealCLanger, we decided against the use of SapMachine in product name because it could use issues in tools/third party applications which parse the product name.
> Please ask @simonis for more details.
Ok, will talk to him. I was not aware of that.

> All other properties are set during SapMachine build. I'd rather not set these values in the source code to avoid potential merge conflicts in the future.
Hm, if you only set the properties in the official builds, private builds will look different and I think that should be avoided. I don't think that these little merge conflicts are problematic at this place. We should discuss that, too.

BTW, I've also seen that the URLs are not correct in my commit. They should have a / at the end. Should we decide to bring the stuff in, I'll update it.

/@RealCLanger :)

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Setting LAUNCHER_NAME=sapmachine and PRODUCT_NAME=SapMachine probably really isn't a great idea. It even fails a few tests.

I just pushed an updated changeset. Let's see if this is better.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Pull request merged**
