### PR TITLE
SAPMachine #253: Fix test jdk/java/net/Socket/ExceptionText.java in sapmachine11

### LINKED ISSUE #253: Fix test jdk/java/net/Socket/ExceptionText.java and move it to tier1
The test jdk/java/net/Socket/ExceptionText.java fails in sapmachine11.

Furthermore, we should add this test to tier1 in order to have it included in the automatic tests for pull requests as it tests a difference to standard OpenJDK.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #253

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by GoeLin** [comment]
Doesn't it make sense to wait with this until 8217657: Move the test for default value of jdk.includeInExceptions into own test is integrated?

**Comment by RealCLanger** [comment]
Hi @GoeLin 

thanks for having a closer look. I removed the changes to the test list and will do that in a separate commit.

I've also withdrawn the pull requests for branches sapmachine and sapmachine12 since the test is not failing there and we should probably wait with cleanup until the change for JDK-8217657 arrives in the SapMachine branches.

However, the currently failing test in sapmachine11 should be fixed, so please review my updated change.

Thanks
Christoph

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Pull request merged**
