### PR TITLE
Backport 8248476: No helpful NullPointerException message after calling fillInStackTrace

### LINKED ISSUE #958: Backport 8248476: No helpful NullPointerException message after calling fillInStackTrace
A fix for the NPE exception message that was also backported "sapmachineonly".
https://bugs.openjdk.java.net/browse/JDK-8248476

### PR DESCRIPTION
**Pull request by GoeLin**
Should have done this long ago...

fixes #958

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Looks good. However, the cacerts test is failing. We need to merge #956 first and then you can rebase your PR. This will then likely turn the required Linux x86_64 PR validation job green. Maybe you want to approve #956 now? 😄

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
Looks good!

**Review by RealCLanger — APPROVED** [review]

**Pull request merged**
