### PR TITLE
SapMachine 18: Merge public jdk 18.0.1

### LINKED ISSUE #1074: Update SapMachine 18 to jdk18u 18.0.1
After the release of SapMachine 18, we can advance the branch to the publicly available commits for OpenJDK 18.0.1.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #1074

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
This looks good. GHA also ok, no idea why it isn't reported here: https://github.com/RealCLanger/SapMachine/actions/runs/2105421597

**Review by ArnoZeller — APPROVED** [review]
Looks good to me.

**Review by chalstrick — APPROVED** [review]

**Pull request merged**
