### PR TITLE
SapMachine #1124: Vitals: June 22 package (SapMachine 18)

### LINKED ISSUE #1124: Vitals: June 22 package
Update Vitals to V3

### PR DESCRIPTION
**Pull request by tstuefe**
Backport to SapMachine 18. I originally thought I can leave this out since 19 is around the corner, but seems not.

As usual, the 18-specific changes you can find in the second commit: ea21757676876853c558a07290c03e74b442aeff

(in this case, I downported the patch from jdk19, not mainline, so the changes are minimal).

Changes:
- Platform.isMusl is missing, I re-added it.

fixes #1124

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by tstuefe** [comment]
Again with the weird GHA mac m1 build.  https://github.com/SAP/SapMachine/runs/7192055302?check_suite_focus=true . It really looks like we build without INCLUDE_NMT. Or with --disable-native-memory-tracking. Our own build works. We had this in the Vitals June 22 patch downport for SapMachine17 too (https://github.com/SAP/SapMachine/pull/1159). But interestingly enough, not in the downport for 11.

While the build error itself is a small issue indirectly caused by the same error that caused us not to be able minimal in 11 and 17, its indicative for something strange, since we never *should* build without NMT. NMT should be always on unless explicitly disabled on the configure command line. But the configure command line for the GHA mac m1 build looks fine.

I cannot reproduce this locally when building on a mac m1, and our Jenkins builds don't fail either, so I ignore it for now.

**Comment by tstuefe** [comment]
All other test errors unrelated.

**Review by schmelter-sap — APPROVED** [review]
The 18 specific changes look good.

**Comment by tstuefe** [comment]
Thanks @schmelter-sap and @RealCLanger !

**Pull request merged**
