### PR TITLE
8244818: Java2D Queue Flusher crash while moving application window t…

### LINKED ISSUE #672: need to cherrypick 8244818 for sapmachine11 and 14
see https://bugs.openjdk.java.net/browse/JDK-8244818

### PR DESCRIPTION
**Pull request by MBaesken**
…o external monitor

Reviewed-by: serb, jdv, kcr

(cherry picked from commit 28b72cb381c1702a8aa5156dbc456cb4c2cf3fe0)

fixes #672

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @MBaesken, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by MBaesken** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

**Comment by reshnm** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

**Pull request merged**
