### PR TITLE
SapMachine #1051: MallocTracer broke Alpine

### LINKED ISSUE #1051: Alpine build broken in all releases because of MallocTracer
The new malloc tracer, introduced with #939, breaks the Alpine build in all jdk releases since its a glibc-only feature and I forgot to correctly ifdef in a couple of places.

### PR DESCRIPTION
**Pull request by tstuefe**
Fixes Alpine build in jdk19

fixes #1051

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Review by RealCLanger — APPROVED** [review]
Looks right.

**Review by ArnoZeller — APPROVED** [review]
Looks good to me.

**Review by MBaesken — APPROVED** [review]

**Comment by tstuefe** [comment]
32-bit error is unrelated (JDK-8282593).

**Pull request merged**
