### PR TITLE
SapMachine (11) #746: Vitals: show global number of processes and tasks

### LINKED ISSUE #746: Vitals: show global number of processes and tasks
When investigating fork failures on our test machines, we found that knowing the global number of processes and tasks (threads) would help a lot.

Only Linux is fine.

### PR DESCRIPTION
**Pull request by RealCLanger**
(cherry picked from commit d365d693aff59b1a0d921cc95ed8e04e7a855bb2)

fixes #746

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Please review/approve. The test failure on MacOS seems unrelated.

**Review by schmelter-sap — APPROVED** [review]
LGTM

**Review by tstuefe — APPROVED** [review]
LGTM. Thanks!

**Review by tstuefe — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
