### PR TITLE
Prepare SapMachine 21

### PR DESCRIPTION
**Pull request by RealCLanger**
Cherry-picks:
8309214: sun/security/pkcs11/KeyStore/CertChainRemoval.java fails after 8301154 to have cleaner tests.
8314960: Add Certigna Root CA - 2

fixes #1502

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
LGTM.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
LGTM

**Review by MBaesken — APPROVED** [review]

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Pull request merged**
