### PR TITLE
SapMachine (22) #1740: Disable experimental and detailed GC events to reduce the file size.

### LINKED ISSUE #1740: Disable experimental and detailed GC events

### PR DESCRIPTION
**Pull request by ansteiner**
(cherry picked from commit https://github.com/SAP/SapMachine/commit/503578bc19c1bdeeee774bd628f9cac3a2253e07)

Didn't apply clean. Resolved conflicts manually.

fixes #1740

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @ansteiner, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by ansteiner** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @ansteiner, this pull request fulfills all formal requirements.

**Review by RealCLanger — APPROVED** [review]
Looks good. Please squash when integrating and clean up commit message to match the one from the initial commit.

**Review by MBaesken — APPROVED** [review]

**Pull request merged**
