### PR TITLE
SapMachine (15) #801: Prepare SapMachine branches for January 2021 release

### LINKED ISSUE #801: Prepare SapMachine branches for January 2021 release
We need to cherry-pick a few test updates and sync the SapMachine specific jtreg exclusion lists in preparation for the January 2021 CPU.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #801

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
This should be reviewed/approved. Only aarch beta job is failing, not related to commits.

**Review by schmelter-sap — APPROVED** [review]
LGTM

**Review by ArnoZeller — APPROVED** [review]
LGTM

**Pull request merged**
