### PR TITLE
SapMachine11: Cherry-pick 8218628: Add detailed message to NullPointerException describing what is null

### LINKED ISSUE #528: Cherry-pick 8218628: Add detailed message to NullPointerException describing what is null to sapmachine11 and 13
See https://bugs.openjdk.java.net/browse/JDK-8218628 and https://openjdk.java.net/jeps/358

### PR DESCRIPTION
**Pull request by GoeLin**
Summary: This is the implementation of JEP 358: Helpful NullPointerExceptions.
Reviewed-by: coleenp, clanger, rschmelter, rriggs, forax, mr

(cherry picked from commit dfdf8d16151bd27aa288b7f7c981e70651350ad8)

The description of this pull request goes here.

fixes #528

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @GoeLin, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by GoeLin** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by GoeLin** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by reshnm** [comment]
> 
> 
> Hi Goetz,
> 
> I squashed your commits and force-pushed to have a single nice commit that can be merged to sapmachine11 via rebase.
> Approving under the assumption build/testing runs well...
> 
> Cheers
> Christoph

Hi,

you could also have squash merged this PR. This would avoid running the complete tests again.

Rene

**Comment by reshnm** [comment]
@GoeLin Windows Test failures: c:/jenkins/workspace/build-11-pr-validation-windows_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp(978): error C2039: 'char_at': is not a member of 'Symbol'
c:\jenkins\workspace\build-11-pr-validation-windows_x86_64\SapMachine\src\hotspot\share\jfr/writers/jfrWriterHost.hpp(37): note: see declaration of 'Symbol'
c:/jenkins/workspace/build-11-pr-validation-windows_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp(978): error C2664: 'void SimulatedOperandStack::push(int,BasicType)': cannot convert argument 1 from 'int' to 'StackSlotAnalysisData'
c:/jenkins/workspace/build-11-pr-validation-windows_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp(978): note: No constructor could take the source type, or constructor overload resolution was ambiguous
c:/jenkins/workspace/build-11-pr-validation-windows_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp(990): error C2039: 'char_at': is not a member of 'Symbol'
c:\jenkins\workspace\build-11-pr-validation-windows_x86_64\SapMachine\src\hotspot\share\jfr/writers/jfrWriterHost.hpp(37): note: see declaration of 'Symbol'
c:/jenkins/workspace/build-11-pr-validation-windows_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp(1140): error C2039: 'char_at': is not a member of 'Symbol'
c:\jenkins\workspace\build-11-pr-validation-windows_x86_64\SapMachine\src\hotspot\share\jfr/writers/jfrWriterHost.hpp(37): note: see declaration of 'Symbol'

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
> > Hi Goetz,
> > I squashed your commits and force-pushed to have a single nice commit that can be merged to sapmachine11 via rebase.
> > Approving under the assumption build/testing runs well...
> > Cheers
> > Christoph
> 
> Hi,
> 
> you could also have squash merged this PR. This would avoid running the complete tests again.
> 
> Rene

Yes, sure. But I rather want to see things clean in the PR. Who knows who will eventually be merging this and whether that guy will use the right options :)

**Comment by RealCLanger** [comment]
> @GoeLin
> **Windows Test failures:**
> _https://ci.sapmachine.io/job/build-11-pr-validation-windows_x86_64/113/console_
> c:/jenkins/workspace/build-11-pr-validation-windows_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp(978): error C2039: 'char_at': is not a member of 'Symbol'
> c:\jenkins\workspace\build-11-pr-validation-windows_x86_64\SapMachine\src\hotspot\share\jfr/writers/jfrWriterHost.hpp(37): note: see declaration of 'Symbol'
> c:/jenkins/workspace/build-11-pr-validation-windows_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp(978): error C2664: 'void SimulatedOperandStack::push(int,BasicType)': cannot convert argument 1 from 'int' to 'StackSlotAnalysisData'
> c:/jenkins/workspace/build-11-pr-validation-windows_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp(978): note: No constructor could take the source type, or constructor overload resolution was ambiguous
> c:/jenkins/workspace/build-11-pr-validation-windows_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp(990): error C2039: 'char_at': is not a member of 'Symbol'
> c:\jenkins\workspace\build-11-pr-validation-windows_x86_64\SapMachine\src\hotspot\share\jfr/writers/jfrWriterHost.hpp(37): note: see declaration of 'Symbol'
> c:/jenkins/workspace/build-11-pr-validation-windows_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp(1140): error C2039: 'char_at': is not a member of 'Symbol'
> c:\jenkins\workspace\build-11-pr-validation-windows_x86_64\SapMachine\src\hotspot\share\jfr/writers/jfrWriterHost.hpp(37): note: see declaration of 'Symbol'
> 
> **macOS Test failures:**
> _https://ci.sapmachine.io/job/build-11-pr-validation-macos_x86_64/112/console_
> Building target 'run-test-gtest' in configuration 'macosx-x86_64-normal-server-release'
> /priv/sapmachine/jenkins/workspace/build-11-pr-validation-macos_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp:978:52: error: no member named 'char_at' in 'Symbol'
> stack->push(bci, char2type((char) signature->char_at(0)));
> ~~~~~~~~~ ^
> /priv/sapmachine/jenkins/workspace/build-11-pr-validation-macos_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp:990:56: error: no member named 'char_at' in 'Symbol'
> stack->pop(type2size[char2type((char) signature->char_at(0))] - Bytecodes::depth(code) - 1);
> ~~~~~~~~~ ^
> /priv/sapmachine/jenkins/workspace/build-11-pr-validation-macos_x86_64/SapMachine/src/hotspot/share/interpreter/bytecodeUtils.cpp:1140:54: error: no member named 'char_at' in 'Symbol'
> return type2size[char2type((char) signature->char_at(0))];
> ~~~~~~~~~ ^

My manual squashing obviously did it wrong. I amended the commit to fix this. The commits that originally belonged to this PR were really inscrutable ;-)

**Comment by reshnm** [comment]
> 
> 
> > > Hi Goetz,
> > > I squashed your commits and force-pushed to have a single nice commit that can be merged to sapmachine11 via rebase.
> > > Approving under the assumption build/testing runs well...
> > > Cheers
> > > Christoph
> > 
> > 
> > Hi,
> > you could also have squash merged this PR. This would avoid running the complete tests again.
> > Rene
> 
> Yes, sure. But I rather want to see things clean in the PR. Who knows who will eventually be merging this and whether that guy will use the right options :)

Ok, but it makes it harder for reviewing when someone introduces during the lifetime of a PR.
When you squash and rebase, I cannot see what has changed since the last commit (resp. failed build).

**Comment by RealCLanger** [comment]
> > > > Hi Goetz,
> > > > I squashed your commits and force-pushed to have a single nice commit that can be merged to sapmachine11 via rebase.
> > > > Approving under the assumption build/testing runs well...
> > > > Cheers
> > > > Christoph
> > > 
> > > 
> > > Hi,
> > > you could also have squash merged this PR. This would avoid running the complete tests again.
> > > Rene
> > 
> > 
> > Yes, sure. But I rather want to see things clean in the PR. Who knows who will eventually be merging this and whether that guy will use the right options :)
> 
> Ok, but it makes it harder for reviewing when someone introduces during the lifetime of a PR.
> When you squash and rebase, I cannot see what has changed since the last commit (resp. failed build).

Yes, incremental commits are good and we should do that. (And squash the stuff then at merge time).
But what I found here was really strange. I think there was one original commit, then another one containing all changes with the modifications and a merge commit. I had a hard time figuring it out - so I decided to clean it up.

**Comment by reshnm** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by reshnm** [comment]
@GoeLin Is this failing test on windows related to this pr?
https://ci.sapmachine.io/job/build-11-pr-validation-windows_x86_64/116/testReport/serviceability_logging_TestQuotedLogOutputs/java/Run_jtreg_hotspot___TestQuotedLogOutputs/

**Comment by GoeLin** [comment]
Hi reshnm, 

The failure is not related to this change. It's a problem with the SapMachine test infrastructure combined with the quoting for windows done by this test.

**Comment by GoeLin** [comment]
Hi RealCLanger, 

I'm trying to understand github and the processes. I'm happy if you tell me what I do wrong.
But I will not understand what is gonig on if you fiddle with my pull requests. 

Thanks, Goetz.

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Pull request merged**
