### PR TITLE
SapMachine #389: Cherry-Pick JDK-8210739: Calling JSpinner's setFont with null throws NullPointerException to SapMachine11

### LINKED ISSUE #389: Cherry-Pick JDK-8210739: Calling JSpinner's setFont with null throws NullPointerException to SapMachine11
The fix for https://bugs.openjdk.java.net/browse/JDK-8210739 has been integrated by Oracle into an 11.0.3 build (b31). Since b31 is probably post ga by Oracle, it won't be taken into SapMachine 11.0.3 ga by default. We could cherry-pick it. It's a very low risk fix for java.desktop.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #389

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
restest this please

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Pull request merged**
