### PR TITLE
SapMachine #1161: SapMachine 17, 11 do not build in minimal (17)

### LINKED ISSUE #1161: SapMachine 17, 11 do not build in minimal
Broken since at least SapMachine #1124. Vitals don't build, INCLUDE_NMT issue.

### PR DESCRIPTION
**Pull request by tstuefe**
Needed manual resolve. Patch is semantically unchanged.

fixes #1161

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Closing, fixed via #1197

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Pull request closed without merging**
