### PR TITLE
change shields.io badge

### LINKED ISSUE #1288: Total number of downloads reported incorrectly
Looks like the shields.io badge for total downloads can currently not handle repositories with large amounts of releases, like SapMachine. The number of total downloads is therefore not correct. See also:
https://github.com/badges/shields/issues/6766

Will remove the badge until fixed.

### PR DESCRIPTION
**Pull request by nice2mitja**
- add a badge for number of downloads for tag "latest"
- remove total downloads, because it's not working.

fixes #1288

### CODE REVIEW

**Review by ArnoZeller — APPROVED** [review]

**Comment by SapMachine** [comment]
Hello @nice2mitja, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @nice2mitja, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @nice2mitja, this pull request fulfills all formal requirements.

**Pull request merged**
