### PR TITLE
SapMachine 271: Update on JSR Expert Groups for Java 16

### PR DESCRIPTION
**Pull request by RealCLanger**
Add JSR 391 membership for Java 16.

fixes #271

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by schmelter-sap — APPROVED** [review]
LGTM

**Review by TheRealMDoerr — APPROVED** [review]

**Pull request merged**
