### PR TITLE
SapMachine (17): Update test exclusion list and fix some bugs pre-release 17.0.4

### LINKED ISSUE #1195: Update SapMachine test exclusion lists and fix some tests
In preparation of the 22/07 update, we can improve our testing setup a little bit.

### PR DESCRIPTION
**Pull request by RealCLanger**
This brings in some fixes for vitals and tests. E.g. #1161 #1172 #1170.

fixes #1195

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by tstuefe — COMMENTED** [review]
Looks good.

**Review by tstuefe — APPROVED** [review]

**Review by ArnoZeller — APPROVED** [review]
LGTM

**Comment by tstuefe** [comment]
A bunch of SA tests fail on MacOS Intel, rest is green.

**Comment by RealCLanger** [comment]
Yep, looks really good.

**Pull request merged**
