### PR TITLE
Merge sapmachine17.0.4.1

### LINKED ISSUE #1229: Merge SapMachine 11.0.16.1 and 17.0.4.1
We need to build SapMachine releases 11.0.16.1 and 17.0.4.1

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #1229

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by TheRealMDoerr — APPROVED** [review]

**Review by schmelter-sap — APPROVED** [review]
Since I see no changes, what could go wrong?

**Comment by RealCLanger** [comment]
GHA issues seem all infrastructure related. Merging.

**Pull request merged**
