### PR TITLE
939 malloc trace facility 11

### PR DESCRIPTION
**Pull request by tstuefe**
Backport of malloc tracer to SapMachine 11 (preparation for SAP JVM backport).

Unfortunately, not a clean backport. A number of changes were necessary.

1) Trivial mechanical changes:

- header changes
	- `memory/allStatic.hpp` -> `memory/allocation.hpp`
	- `jvm_io.h` -> `jvm.h`
	
- Prototype of `Atomic::cmpxchg` changed

- Different include order

- C++11 not available, `enum class` -> `enum`

More complex changes:

- `os::print_function_and_library_name()` not available in 11. I copied that one into `siteTable.cpp` as local static helper in an abridged version (does not handle function descriptors, but this does not matter here)

- The gtest suite in 11u misses the whole `ConcurrentTestRunner` framework for running multithread tests. I just removed the associated tracer test which uses this framework.

- In JDK17, when printing out stacks, we also resolve compiled methods in code cache (see `sap::Stack::print_on()`). That coding differs in 11u. To keep matters simple - since this feature is not that useful anyway - I just disabled it for 11u.

- Needed to provide `MallocTraceDCmd::num_arguments()`	for the jdk11 version of the `MallocTraceDCmd` - in later versions that is not necessary, so this is a bit of a backport trap. Omitting that led to a C heap overwrite in `jmm_GetDiagnosticCommandArgumentsInfo`. A fix has been made independently to prevent such errors in the future, see https://bugs.openjdk.java.net/browse/JDK-8277029.

Test: We ran this a couple of nights as patch in jdk11u, to no adverse affects. The only issue cropping up was on s390, where stack walking is not robust enough to be used from arbitrary sample points. However, this is an s390 specific issue and of no relevance to SapMachine 11, since we don't do s390.

There are a small number of test failures on ppc64le, but they have nothing to do with the malloc tracer, which is not even enabled at that point.

fixes #985

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by SapMachine** [comment]
Hello @tstuefe, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Review by RealLucy — APPROVED** [review]
Looks good to me.

**Comment by tstuefe** [comment]
> Looks good to me.

Thank you, Lutz!

**Review by MBaesken — APPROVED** [review]

**Pull request merged**
