### PR TITLE
Merge to tag jdk-20+14

### PR DESCRIPTION
**Pull request by SapMachine**
please pull

### CODE REVIEW

**Comment by RealCLanger** [comment]
@tstuefe Can you please have a look at the GHA build failures on Linux?

**Comment by tstuefe** [comment]
@RealCLanger this may take a day or two since I need to resolve malloc hooks dynamically (I assume we now build on newer glibcs).

**Comment by tstuefe** [comment]
Done

**Comment by tstuefe** [comment]
Test errors related to problems with Shenandoah + sweeper removal.

**Review by MBaesken — APPROVED** [review]

**Review by RealCLanger — APPROVED** [review]

**Pull request merged**
