### PR TITLE
Cherry-pick JDK-8034802 to sapmachine11

### LINKED ISSUE #259: Cherry-pick JDK-8034802 to sapmachine11
JDK-8034802 needs to be cherry-picked to sapmachine11. It is kind of a prerequisite for the enhancements to zipfs regarding Posix permissions. It is needed to fix issues shown by its jtreg testcase jdk/nio/zipfs/TestPosixPerms.java. A downport to jdk11u will be requested in the OpenJDK as well.

### PR DESCRIPTION
**Pull request by RealCLanger**
Change:
http://hg.openjdk.java.net/jdk/jdk/rev/ba51515b64e5
8034802: (zipfs) newFileSystem throws UOE when the zip file is located in a custom file system
author: sherman
Reviewed-by: xiaofeya, clanger

As the patch did not apply cleanly, it had to be modified in a few places.

fixes #259

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by ArnoZeller** [comment]
retest this please.

**Comment by ArnoZeller** [comment]
retest this please

**Comment by ArnoZeller** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Pull request merged**
