### PR TITLE
Adding JDK18 and JDK19

### PR DESCRIPTION
**Pull request by nice2mitja**
Add some details about JDK18 and upcoming JDK19

fixes #271

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @nice2mitja, this pull request fulfills all formal requirements.

**Review by RealLucy — APPROVED** [review]
Looks good.

**Review by ArnoZeller — APPROVED** [review]

**Review by RealCLanger — APPROVED** [review]
I fixed two link titles for JSR 393 and JSR 394 directly in the source branch. Please squash&merge 😄

**Comment by SapMachine** [comment]
Hello @nice2mitja, this pull request fulfills all formal requirements.

**Pull request merged**
