### PR TITLE
SapMachine(12) 335: Add a preliminary fix for JDK-8200286 to test it

### LINKED ISSUE #335: Add a preliminary fix for JDK-8200286 to test it
On LinuxPPC64 we see the problem described in OpenJDK bug https://bugs.openjdk.java.net/browse/JDK-8200286.

I'd like to bring a fix for it to OpenJDK, but we should add it to SapMachine before in order to test and see if it really resolves the problem.

### LINKED ISSUE #355: Make posix_spawn the preferred launch mechanism on SapMachine12
POSIX_SPAWN shall be the default launch mechanism on Linux.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #335

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, I'm sorry, this pull request doesn't meet the expectations. tuple index out of range Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by ArnoZeller** [comment]
Mac shows OOM - we might increase heap for langtools test a bit more.

**Pull request merged**
