### PR TITLE
Merge to tag jdk-11.0.7+3

### PR DESCRIPTION
**Pull request by SapMachine**
please pull

### CODE REVIEW

**Comment by reshnm** [comment]
Windows test failed:

https://ci.sapmachine.io/job/build-11-pr-validation-windows_x86_64/153/testReport/junit/serviceability_sa_ClhsdbJstackXcompStress/java/Run_jtreg_hotspot___ClhsdbJstackXcompStress/

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
> Windows test failed:
> 
> https://ci.sapmachine.io/job/build-11-pr-validation-windows_x86_64/153/testReport/junit/serviceability_sa_ClhsdbJstackXcompStress/java/Run_jtreg_hotspot___ClhsdbJstackXcompStress/

I think I've seen this intermittently in our OpenJDK test environment. I retriggered the tests, let's see if it reproduces.

**Comment by reshnm** [comment]
> > Windows test failed:
> > https://ci.sapmachine.io/job/build-11-pr-validation-windows_x86_64/153/testReport/junit/serviceability_sa_ClhsdbJstackXcompStress/java/Run_jtreg_hotspot___ClhsdbJstackXcompStress/
> 
> I think I've seen this intermittently in our OpenJDK test environment. I retriggered the tests, let's see if it reproduces.

The test failed again.

**Comment by RealCLanger** [comment]
> > > Windows test failed:
> > > https://ci.sapmachine.io/job/build-11-pr-validation-windows_x86_64/153/testReport/junit/serviceability_sa_ClhsdbJstackXcompStress/java/Run_jtreg_hotspot___ClhsdbJstackXcompStress/
> > 
> > 
> > I think I've seen this intermittently in our OpenJDK test environment. I retriggered the tests, let's see if it reproduces.
> 
> The test failed again.

This seems like an occurence of this bug, which is not solved upstream:
https://bugs.openjdk.java.net/browse/JDK-8204994

Interestingly, it reproduced. However, I think we should merge this PR nevertheless.

**Pull request merged**
