### PR TITLE
SapMachine #747: Vitals: display commit state on Linux

### LINKED ISSUE #747: Vitals: display commit state on Linux
When investigating fork failures on our test machines, we found that knowing the current commit charge would help (how much we are overcommitted).

Only Linux is fine.

### PR DESCRIPTION
**Pull request by tstuefe**
Add a column to the output - linux only - which displays overcommit state. Helps in analyzing allocation- and thread/fork-failures.

Looks like this:

```
  1 Vitals:
  2 ------------system------------
<snip>
  4              crt: Committed-to-Commit-Limit ratio (percent)
<snip>
 51 Short Term Values:
 52                       -------------------system------------------- -------------------process-------------------- ------------------------------------jvm------------------------------------
 53                                                  -------cpu-------      -------rss-------      -cpu- ---io---     --heap--- ---------meta---------          ----jthr----- --cldg-- ---cls----
 54 Time                  avail crt swap si so pr pb us sy id wa st gu virt all anon file shm swdo us sy of rd wr thr comm used comm used csc csu gctr code mlc num nd cr st  num anon num ld uld
 55 
 56 2020-11-02 11:19:03   10,5g 108 256k        3  0                   6,6g 69m  37m  32m  0k   0k        2        18 254m   3m 192k 111k 64k  2k  21m   7m  0k   9  1    16m   3    0 447
```

Column "crt" shows overcommit state, in percent (108 in my case)

fixes #747

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Review by RealCLanger — APPROVED** [review]
LGTM

**Review by schmelter-sap — APPROVED** [review]
LGTM

**Pull request merged**
