### PR TITLE
SapMachine (11) #1051: MallocTracer broke Alpine

### LINKED ISSUE #1051: Alpine build broken in all releases because of MallocTracer
The new malloc tracer, introduced with #939, breaks the Alpine build in all jdk releases since its a glibc-only feature and I forgot to correctly ifdef in a couple of places.

### PR DESCRIPTION
**Pull request by tstuefe**
Fixes Alpine build in jdk11

fixes #1051

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by tstuefe** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Review by RealCLanger — APPROVED** [review]

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
Looks good to me.

**Comment by tstuefe** [comment]
Errors seem unrelated

**Pull request merged**
