### PR TITLE
jcmd GC.heap_dump without options should write to location given by -XX:HeapDumpPath, if set

### LINKED ISSUE #1670: jcmd GC.heap_dump without options should write to location given by -XX:HeapDumpPath, if set
Currently jcmd command GC.heap_dump only works with an additionally provided file name.
Syntax : GC.heap_dump [options] <filename>

In case the JVM has the XX-flag HeapDumpPath set, we should support an additional mode where the <filename> is optional.
In case the filename is NOT set, we take the HeapDumpPath (file or directory).

new syntax :
GC.heap_dump [options] <filename> ... has precedence over second option
GC.heap_dump [options] … in case -XX:HeapDumpPath=p is set

This would be a simplification e.g. for support cases where a filename or directory is set at JVM startup with -XX:HeapDumpPath=p and writing to the path is intended/recommended for usage also in the jcmd case.

See also https://bugs.openjdk.org/browse/JDK-8327769

### PR DESCRIPTION
**Pull request by MBaesken**
See https://bugs.openjdk.org/browse/JDK-8327769

The description of this pull request goes here.

fixes #1670

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

**Review by ansteiner — APPROVED** [review]
LGTM

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
LGTM

**Pull request merged**
