### PR TITLE
Merge to tag jdk-20+13

### PR DESCRIPTION
**Pull request by SapMachine**
please pull

### CODE REVIEW

**Review by TheRealMDoerr — CHANGES_REQUESTED** [review]
CONFLICT (content): Merge conflict in src/hotspot/share/runtime/java.cpp

**Comment by RealCLanger** [comment]
> CONFLICT (content): Merge conflict in src/hotspot/share/runtime/java.cpp

I've resolved it. Let's see if Windows builds now in our CI... 😄

**Review by schmelter-sap — APPROVED** [review]
LGTM

**Review by MBaesken — APPROVED** [review]

**Review by TheRealMDoerr — APPROVED** [review]
Thanks for fixing it. The new test failures are known.

**Pull request merged**
