### PR TITLE
Implement Statistical History for JDK12

### LINKED ISSUE #241: A low-cost, always on statistical value history (JDK-8212618)
This issue tracks development of [JDK-8212618 "A low-cost, always on statistical value history"](https://bugs.openjdk.java.net/browse/JDK-8212618). 

This proposed feature has been rejected upstream since it is perceived to collide with JMC/JFR.
We consider it useful enough and the merge cost to be small enough to integrate it into the SapMachine. 

Details:

SAP developed a supportability feature called "Statistics History" which is a low cost history of statistical values-of-interest. 

These values contain parameters of the jvm (e.g. heap size, metaspace size, number of loaded classes) and the underlying platform (e.g. rss, swapping state, run queue length etc). At intervals of (by default) 60 seconds these values are measured and stored in a fifo buffer. 

The fifo buffer has three parts, a short-, medium-, and long term fifo buffer. A fraction of the samples falling out of the short term fifo is transferred to the mid term fifo; again, a fraction of the samples falling out of the mid term fifo is transferred to the long term fifo. So, the short term fifo covers a short recent timespan (usually an hour) in comparativly short sample intervals (usually 60 seconds), whereas the long term fifo covers a very long time span (~10 days) with interval times of hours. 

This feature has been very popular with our support folks and so we would like to contribute that. It enables us to easily analyze slowly developing situations like memory leaks, memory or cpu spikes, resource starvation etc. 

[\[1\] JDK-8212618 - Original JBS issue, closed as Wont Fix](https://bugs.openjdk.java.net/browse/JDK-8212618)
[\[2\] Patch on Github](https://github.com/tstuefe/ojdk-stathist-patch)
[\[3\] Example output](http://cr.openjdk.java.net/~stuefe/webrevs/stathist/examples/dacapo.txt)

### PR DESCRIPTION
**Pull request by tstuefe**
Implement Statistical History for JDK12.

fixes #241

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
After internal discussion, we decided to merge this PR after 12-ga.

**Comment by RealCLanger** [comment]
I pushed the changes to the SAP license header to this PR, so they'll be merged. The rest of sapmachine12 branch is fine in terms of license headers.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by tstuefe** [comment]
Mac OS fests failed, Windows tests hang. Can someone pls take a look or tell me what to do? I do not see any test results, clicking on "Details" just times out.

**Comment by RealCLanger** [comment]
> Mac OS fests failed, Windows tests hang. Can someone pls take a look or tell me what to do? I do not see any test results, clicking on "Details" just times out.

No worries. Windows is still running and Mac runs in a known OOM. I can show you how to access the thest results and read it face 2 face...

**Pull request merged**
