### PR TITLE
SapMachine (15) #560: When printing/dumping Vitals in csv format there are duplicate column names

### LINKED ISSUE #560: When printing/dumping Vitals in csv format there are duplicate column names
"cpu-us" and "cpu-sy" appear twice since we print them once as the system totals, once as process values. Lets fix this and assert for double column names .

### PR DESCRIPTION
**Pull request by RealCLanger**
(cherry picked from commit 14d1d0ef7df725757a171fb5f93824bdaf2e43d8)

fixes #560

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by schmelter-sap — APPROVED** [review]
Sieht bekannt aus

**Review by tstuefe — APPROVED** [review]

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Pull request merged**
