### PR TITLE
Merge to tag jdk-16+24

### PR DESCRIPTION
**Pull request by SapMachine**
please pull

### CODE REVIEW

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
retest this please

**Review by TheRealMDoerr — APPROVED** [review]

**Review by RealCLanger — APPROVED** [review]

**Pull request merged**
