### PR TITLE
Sapmachine #1058: Vitals: Integrate March 2022 updates (18)

### LINKED ISSUE #1058: Vitals: Integrate March 2022 updates
Vitals have gotten a number of improvements. Its time to bring those to SapMachine, SAPJVM.

### PR DESCRIPTION
**Pull request by tstuefe**
Clean backport.

fixes #1058

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by tstuefe** [comment]
retest please

**Comment by tstuefe** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Pull request closed without merging**
