### PR TITLE
SapMachine #1331: Add additional Flight Recorder configurations specific for GC profiling

### LINKED ISSUE #1331: Provide additional Flight Recorder configurations specific for GC profiling
Provide additional Flight Recorder configurations specific for GC profiling. A lightweight configuration with small recording size, which can be also used for longer profiling runs with low overhead. A very detailed configuration for detailed GC analysis, with higher impact caused by heap inspection initiated GCs and large recording size.

### PR DESCRIPTION
**Pull request by ansteiner**
Add additional Flight Recorder configurations specific for GC profiling. A lightweight configuration with small recording size, which can be also used for longer profiling runs with low overhead. A very detailed configuration for detailed GC analysis, with higher impact caused by heap inspection initiated GCs and large recording size.

fixes #1331

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @ansteiner, this pull request fulfills all formal requirements.

**Review by RealCLanger — APPROVED** [review]
Looks good. I assume these files get copied over automatically to the JDK image?

**Comment by RealCLanger** [comment]
When you merge, can you please do "Squash and merge" to change the commit comment to "SapMachine #1331: Add additional Flight Recorder configurations specific for GC profiling" that #1331 is referenced from the commit. Thanks.

**Comment by ansteiner** [comment]
> Looks good. I assume these files get copied over automatically to the JDK image?

Yes, all jfc files in the directory are copied.

**Review by parttimenerd — APPROVED** [review]

**Comment by SapMachine** [comment]
Hello @ansteiner, this pull request fulfills all formal requirements.

**Pull request merged**
