### PR TITLE
SapMachine(11) #368: Cherry-pick changes of JDK-8221610: Resurrect (legacy) JRE bundle target

### LINKED ISSUE #368: Cherry-pick changes of JDK-8221610: Resurrect (legacy) JRE bundle target
The changes of https://bugs.openjdk.java.net/browse/JDK-8221610 (Resurrect (legacy) JRE bundle target) should be picked to SapMachine 11 and 12 to enable build script simplification.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #368

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Pull request merged**
