### PR TITLE
SapMachine #761: Fix Github Actions Pre-Submit Tests

### LINKED ISSUE #761: Fix Github Actions Pre-Submit Tests
OpenJDK has defined pre-submit tests for branches/pull requests. Those don't work on sapmachine, because the jdk and test bundle names in SapMachine are slightly different.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #761

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
Looks good to me.
Windows Linuxppc64le and aarch had other issues.

**Review by TheRealMDoerr — APPROVED** [review]

**Pull request merged**
