### PR TITLE
add JDK-8210964 - add more ld preloading info to hs_error file on Linux

### PR DESCRIPTION
**Pull request by MBaesken**
(hand integrated)

### CODE REVIEW

**Comment by reshnm** [comment]
JDK Test ["jdk/jfr/event/gc/configuration/TestGCConfigurationEvent.java"](https://ci.sapmachine.io/job/test-jtreg-jdk-11-pr-validation/20/JT_20Report/) failed.
I don't know whether this is related to this changed.

**Comment by reshnm** [comment]
retest this please

**Comment by GoeLin** [comment]
Hi Volker,

Matthias just did what was discussed in the last team meeting.
Maybe some details need to settle, but basically this is what
we decided on.

Best regards,
  Goetz.

**Comment by reshnm** [comment]
retest this please

**Comment by simonis** [comment]
Maybe it is my fault that I've not been at the last team meeting but I can not agree to what you've decided.

It makes absolutely no sense to "hand-integrate" pure OpenJDK changes from newer to older code-lines with a changed "summary" and countless "//SapMachine" comments mangled in. This isn't done in the OpenJDK either (e.g. you don't change a patch when downporting from the head to an update revision).

With Git we have better tooling compared to OpenJDK's Mercurial so simple downports should be nothing more than a simple cherry-pick from one branch into another. This has the additional advantage that Git will be easily able to track and detect such changes if they will flow back from the upstream repository because the OpenJDK update project maintainers have decided to downport the same change. With the current approach that will just lead to a bunch of merge conflicts.

Instead of polluting the sources with comments I'd recommend to open a new issue for each downport to track them more easily.

I'm of course also open to discuss this topic in our next meeting :)

**Comment by reshnm** [comment]
retest this please

**Comment by reshnm** [comment]
retest this please

**Comment by simonis** [comment]
Will come in automatically from the upstream jdk-updates/jdk11u repository.

**Pull request closed without merging**
