### PR TITLE
SapMachine #1124: Vitals: June 22 package (SapMachine 11)

### LINKED ISSUE #1124: Vitals: June 22 package
Update Vitals to V3

### PR DESCRIPTION
**Pull request by tstuefe**
Backport of Vitals June 22 for JDK 11.

For 11-related delta to the base patch see commit adcd5306ae3d21d06bf786f319fb24208c7608be.

Those fixes are:
- Cannot use C++11 enum classes or "override"
- os::naked_sleep() does not exist
- os::file_exists() missing
- Platform.isMuslc() in jtreg missing
- this is before the thread.cpp split, so "threads.cpp" does not exist yet
- Testwise, jcmd VM.metaspace provides slightly different results, and we have no class loader graph information in vitals, so no "cldg" columns

The rest is small stuff (includes renamed etc)

fixes #1124

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by tstuefe** [comment]
All checks green save for the minimal build (which will be fixed with #1165)

**Review by RealCLanger — APPROVED** [review]
Looks good. I assume the error in GHA [Linux additional (hs x64 minimal build only)](https://github.com/SAP/SapMachine/runs/7161609056?check_suite_focus=true#logs) is fixed via #1161 ?

**Pull request merged**
