### PR TITLE
Add jcmd to jre17

### LINKED ISSUE #960: Deliver jcmd in jre
Some customer wants to have the jcmd tool in the JRE provided by SapMachine 11 and 17.
So we need to put the tool and related classes (modules) into the JRE.

### PR DESCRIPTION
**Pull request by MBaesken**
This adds jcmd to the legacy JRE 17.

fixes #960

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @MBaesken, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
Looks good.
The windows error seems to be completely unrelated.

**Review by RealCLanger — APPROVED** [review]

**Pull request merged**
