### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skateball**
(down)port of changes from sapmachine.io to here

fixes #271

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @skateball, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @skateball, this pull request fulfills all formal requirements.

**Review by RealCLanger — APPROVED** [review]
LGTM.

@nice2mitja @GoeLin WDYT?

**Review by GoeLin — APPROVED** [review]
LGTM

**Pull request merged**
