### PR TITLE
SapMachine #285: Update SapMachine specific problem lists

### LINKED ISSUE #285: Update SapMachine specific problem lists
The SapMachine specific problem lists need an update.

- Merge with the internal problem lists that SAP uses for OpenJDK regression testing
- Add SapMachine infrastructure specific exclusions to reduce the number of false positives when running platform builds

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #285

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Hi Goetz

> * SapMachine 2018-01-18 Failing tests after fix for 8215544. Need to check.
>   Please write instead
>   "Fixed by 8217473: SA: Tests using ClhsdbLauncher fail on SAP docker containers"

Done, thanks for the heads up. So we should be able to remove this section next week then anyway :)

> Why do you remove the solaris lines?
> -com/sun/nio/sctp/SctpChannel/Bind.java solaris-sparcv9
> I understand we don't build solaris, but it would make diffing the
> files more easy.

Ok, I went another round and included everything from the internal list also for platforms that we don't support. I agree, it makes it easier to diff the files line by line.

> We should do aother update after 7.2.2019, which is end of rdp1 for 12.
> Then we can check the OpenJDK exclude list against a stable target, maybe some
> of the issues got fixed in the meantime.

Sure, we should update this as often as possible :)

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Pull request merged**
