### PR TITLE
SapMachine #506: Increase Vitals range for short term table

### LINKED ISSUE #506: Increase Vitals range for short term table
Currently the short term history of the Vitals covers 15 minutes with a default sample interval of 15 seconds. That is not enough. Increase the value to cover at least an hour.

### PR DESCRIPTION
**Pull request by tstuefe**
Increase Vitals range for short term table

fixes #506

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by reshnm** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by reshnm** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Pull request merged**
