### PR TITLE
SapMachine #1073: Process on exit error

### LINKED ISSUE #1073: Process OnExitTest keeps failing on ppc and aarch64
... SapMachine11 only.

### PR DESCRIPTION
**Pull request by tstuefe**
in process. Please ignore.

fixes #1073

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by tstuefe** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Pull request closed without merging**
