### PR TITLE
SapMachine #1162: Vitals: Initialization should not rely on &= short-circuiting

### LINKED ISSUE #1162: Vitals: Initialization should not rely on &= short-circuiting
Found by Ralf. See sapmachine_vitals::initialize().

### PR DESCRIPTION
**Pull request by tstuefe**
I did use &= in a number of places for brevity, thinking it would short-circuit, but it won't, not in C++.

fixes #1162

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by tstuefe** [comment]
Test errors unrelated to this patch

**Review by RealCLanger — APPROVED** [review]

**Comment by tstuefe** [comment]
test errors unrelated

**Review by ArnoZeller — APPROVED** [review]
Looks good to me.

**Pull request merged**
