### PR TITLE
SapMachine (21) #1611: Fix SapMachine build after: Add dt_filesocket to sapmachine21

### PR DESCRIPTION
**Pull request by RealCLanger**
The build fails on AIX.

fixes #1611

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by MBaesken — APPROVED** [review]

**Review by schmelter-sap — APPROVED** [review]
Looks good to me.

**Pull request merged**
