### PR TITLE
SapMachine (22) #1693: Support starting child processes in an own process group (unix only)

### PR DESCRIPTION
**Pull request by RealCLanger**
(cherry picked from commit cee6c5e72f73121e8aff985553cc9fc12b6a6e73)

with minor modifications

fixes #1693

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by schmelter-sap — APPROVED** [review]
Looks good.

**Review by ArnoZeller — APPROVED** [review]
LGTM

**Pull request merged**
