### PR TITLE
SapMachine #1161: SapMachine 17, 11 do not build in minimal (19)

### LINKED ISSUE #1161: SapMachine 17, 11 do not build in minimal
Broken since at least SapMachine #1124. Vitals don't build, INCLUDE_NMT issue.

### PR DESCRIPTION
**Pull request by tstuefe**
Needed manual resolve. Patch is semantically unchanged.

fixes #1161

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by tstuefe** [comment]
Linux x64 build error (memset zero len parm) unrelated to this patch, already fixed upstream with https://bugs.openjdk.org/browse/JDK-8289799

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Review by RealCLanger — APPROVED** [review]
Failures on Alpine and Mac are known.

**Pull request merged**
