### PR TITLE
SapMachine #512: Make file name for DumpVitalsAtExit configurable

### LINKED ISSUE #512: Make file name for DumpVitalsAtExit configurable
For automated scripting it makes sense to be able to set the output file name for the vitals dumped at vm exit.

### PR DESCRIPTION
**Pull request by tstuefe**
fixes #512

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Hey Thomas,
I think this is useful. It would be nice though if one could specify a placeholder that gets substituted with the pid in the new filename option, e.g. <pid>. What do you think?
Best regards 
Christoph

**Comment by tstuefe** [comment]
> Hey Thomas,
> I think this is useful. It would be nice though if one could specify a placeholder that gets substituted with the pid in the new filename option, e.g. . What do you think?
> Best regards
> Christoph

Hi Christoph,

Okay, but can we just merge this one and add placeholders later if needed?

Personally, I find the "pid" placeholder is not used much in reality. The point of this particular pull request is exactly to avoid the "randomness" of a pid in the name, to simplify automatic processing.

Cheers, Thomas

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Hi Thomas,

> Okay, but can we just merge this one and add placeholders later if needed?
> 
> Personally, I find the "pid" placeholder is not used much in reality. The point of this particular pull request is exactly to avoid the "randomness" of a pid in the name, to simplify automatic processing.

It was just an idea. But maybe you're right. For scripting you don't want the pid and for other use cases such as a server that is restarted recently one would probably not use the pid placeholder as well since otherwise over time a bunch of such files would accumulate. So let's forget about this until somebody asks for it with a strong usecase :)

/Christoph

**Pull request merged**
