### PR TITLE
SapMachine(11) #330: Reduce SapMachine specific exclusion list for jdk jtreg tests

### LINKED ISSUE #320: Update SapMachine branding
There are several places in OpenJDK where vendors can add their branding information. This gets effective in e.g. System properties, executable meta information, icons etc. SapMachine should make use of this.

### LINKED ISSUE #330: Reduce SapMachine specific exclusion list for jdk jtreg tests
The SapMachine specific exclusion list for jdk jtreg tests can (hopefully) be reduced a bit.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #330

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by reshnm** [comment]
@RealCLanger wrong issue linked?
I guess it should be #330 instead of #320

**Comment by RealCLanger** [comment]
> @RealCLanger wrong issue linked?
> I guess it should be #330 instead of #320

yep 👍

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
> As far as I see only com/sun/jdi/JdbExprTest.sh was removed?
> LGTM 👍

yes. The pull requests to the other branches also removes the exclusion of jdk/modules/scenarios/overlappingpackages/OverlappingPackagesTest.java which got fixed via the latest jtreg updates. But this was never excluded in sapmachine11, so it's effectively only JdbExprTest.sh and the reordering.

**Pull request merged**
