### PR TITLE
SapMachine (11): Update test exclusion list and fix some bugs pre-release 11.0.16

### LINKED ISSUE #1195: Update SapMachine test exclusion lists and fix some tests
In preparation of the 22/07 update, we can improve our testing setup a little bit.

### PR DESCRIPTION
**Pull request by RealCLanger**
This brings in some fixes for vitals and tests. E.g. #1161 #1172 #1170.

fixes #1195

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
+1

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by schmelter-sap — APPROVED** [review]
LGTM

**Review by ArnoZeller — APPROVED** [review]
LGTM.

**Comment by RealCLanger** [comment]
Looks perfect 😄

**Pull request merged**
