### PR TITLE
SapMachine13: Cherry-pick 8218628: Add detailed message to NullPointerException describing what is null

### LINKED ISSUE #528: Cherry-pick 8218628: Add detailed message to NullPointerException describing what is null to sapmachine11 and 13
See https://bugs.openjdk.java.net/browse/JDK-8218628 and https://openjdk.java.net/jeps/358

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #528

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by GoeLin** [comment]
Looks good, thanks!

**Pull request merged**
