### PR TITLE
Excluded serviceability/jvmti/8036666/GetObjectLockCount.java test on macOS

### LINKED ISSUE #659: Exclude serviceability/jvmti/8036666/GetObjectLockCount.java test
This test fails on our macOS test infrastructure due to the SAP specific DNS.

### PR DESCRIPTION
**Pull request by reshnm**
fixes #659

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
PS: When you merge, can you please squash and modify the commit message to "SapMachine #659: ..."? Thanks :)
And we should cherry-pick to 15.

**Comment by reshnm** [comment]
> PS: When you merge, can you please squash and modify the commit message to "SapMachine #659: ..."? Thanks :)
> And we should cherry-pick to 15.

Of course :-)

**Comment by RealCLanger** [comment]
I've merged it to retest the new PRs...

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @reshnm, this pull request fulfills all formal requirements.

**Pull request merged**
