### PR TITLE
SapMachine #1332: Vitals log should be less chatty

### LINKED ISSUE #1332: Vitals log should be less chatty
`-Xlog:vitals` is too chatty. It should be less chatty.

In particular, it should not dump all information about cgroups init at info level.

### PR DESCRIPTION
**Pull request by tstuefe**
Lowers the log level for vitals log in cgroup initialization from info to debug/trace.

fixes #1332

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Review by parttimenerd — APPROVED** [review]

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by tstuefe** [comment]
Remaining errors have nothing to do with my patch:
- windows x64 is an infrastructure problem
- ppcle is an assert in `GetStackTraceSuspendedStressTest`, nothing to do with my change. I pinged Richard and Martin.

**Review by RealCLanger — APPROVED** [review]

**Comment by RealCLanger** [comment]
Should be good now. ppc64le verifcation error unrelated.

**Pull request merged**
