### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by koppor**
There is no apostrophe for plural s in English (also not in German BTW).

(Link: Its not possessive - see https://www.oxfordlearnersdictionaries.com/grammar/online-grammar/possessive-s-and-s.)

fixes #480

### CODE REVIEW

**Comment by SapMachine** [comment]
Hi @koppor. Thanks for your Pull Request. I'm waiting for a [SapMachine Team member](https://github.com/orgs/SAP/teams/sapmachine-team) to verify that this pull request is ok to test. If it is, they should reply with `retest this please`.

**Comment by RealCLanger** [comment]
retest this please

**Comment by RealCLanger** [comment]
retest this please

**Review by RealCLanger — APPROVED** [review]
Did some research about english grammar because I thought there are valid cases where in plurals the apostrophe is used. Result: There are, but not in cases like that one. 😄 So you are right.

**Comment by koppor** [comment]
> Did some research about english grammar because I thought there are valid cases where in plurals the apostrophe is used. Result: There are, but not in cases like that one. 😄 So you are right.

Thank you for double checking!

I was recommended https://theoatmeal.com/comics/apostrophe. 😅

**Comment by SapMachine** [comment]
Hello @koppor, this pull request fulfills all formal requirements.

**Pull request merged**
