### PR TITLE
Switch off OmitStackTraceInFastThrow to get verbose exceptions for op…

### LINKED ISSUE #501: Switch off OmitStackTraceInFastThrow to get verbose exceptions for optimized code
OmitStackTraceInFastThrow is an optimization in hotspot that uses preallocated exceptions in highly optimized code. This saves the time to allocate the exception object. But the preallocated exceptions have no message nor a stack trace.

Code that has exception handling that gets hot enough to get optimized this way is a flawy design. Instead of omitting the exception information it should be delivered to the user so he can spot the issue and fix it. Thus, we disable this optimization in SapMachine.

### PR DESCRIPTION
**Pull request by GoeLin**
…timized code

fixes #501

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Hi Goetz,

when merging, can you please squash and change your commit message to:

SapMachine #501: Switch off OmitStackTraceInFastThrow to get verbose exceptions for optimized code

Thanks
Christoph

**Comment by SapMachine** [comment]
Hello @GoeLin, this pull request fulfills all formal requirements.

**Comment by GoeLin** [comment]
I want to have a look at the deoptimization that causes some tests to time out.
Won't do this in near future ... so closing the PR for now.

**Pull request closed without merging**
