### PR TITLE
SapMachine (22) #1611: Implement dt_filesocket for sapmachine 17+

### PR DESCRIPTION
**Pull request by RealCLanger**
cherry picked from commit 1e9c4a00253bd6ceb2b31ae28880a31bd0d0046a and made minor modifications in makefiles

fixes #1611

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by MBaesken — APPROVED** [review]

**Review by schmelter-sap — APPROVED** [review]
Looks good to me.

**Comment by RealCLanger** [comment]
outstanding PR validation jobs are beyond builds, looking good.

**Pull request merged**
