### PR TITLE
Refresh sapmachine17

### LINKED ISSUE #967: Refresh SapMachine 17 for 17.0.1
For the upcoming October update we shall sync the public changes from jdk17u for 17.0.1 plus cherry-pick a few OpenJDK changes that we deem necessary to go into SapMachine's 17.0.1 release.

### PR DESCRIPTION
**Pull request by RealCLanger**
Changes for SapMachine 17.0.1.

fixes #967

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Now this contains all commits we know of in jdk17u that we want to have for 17.0.1. Please approve (when the tests are through). I will then rebase #965

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by MBaesken — APPROVED** [review]

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
Looks good. Especially fixing the disturbing certificate test!

**Pull request merged**
