### PR TITLE
Stathist 11

### LINKED ISSUE #241: A low-cost, always on statistical value history (JDK-8212618)
This issue tracks development of [JDK-8212618 "A low-cost, always on statistical value history"](https://bugs.openjdk.java.net/browse/JDK-8212618). 

This proposed feature has been rejected upstream since it is perceived to collide with JMC/JFR.
We consider it useful enough and the merge cost to be small enough to integrate it into the SapMachine. 

Details:

SAP developed a supportability feature called "Statistics History" which is a low cost history of statistical values-of-interest. 

These values contain parameters of the jvm (e.g. heap size, metaspace size, number of loaded classes) and the underlying platform (e.g. rss, swapping state, run queue length etc). At intervals of (by default) 60 seconds these values are measured and stored in a fifo buffer. 

The fifo buffer has three parts, a short-, medium-, and long term fifo buffer. A fraction of the samples falling out of the short term fifo is transferred to the mid term fifo; again, a fraction of the samples falling out of the mid term fifo is transferred to the long term fifo. So, the short term fifo covers a short recent timespan (usually an hour) in comparativly short sample intervals (usually 60 seconds), whereas the long term fifo covers a very long time span (~10 days) with interval times of hours. 

This feature has been very popular with our support folks and so we would like to contribute that. It enables us to easily analyze slowly developing situations like memory leaks, memory or cpu spikes, resource starvation etc. 

[\[1\] JDK-8212618 - Original JBS issue, closed as Wont Fix](https://bugs.openjdk.java.net/browse/JDK-8212618)
[\[2\] Patch on Github](https://github.com/tstuefe/ojdk-stathist-patch)
[\[3\] Example output](http://cr.openjdk.java.net/~stuefe/webrevs/stathist/examples/dacapo.txt)

### PR DESCRIPTION
**Pull request by tstuefe**
A low-cost, always on statistical value history (JDK-8212618)

fixes #241

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Hi Thomas,

to me, it seems that this is not the merged version of the sapmachine branch after review, but rather the initial version (e.g. you made some fixes after review from Ralf). It also doesn't contain the license heder updates I did later on. Maybe you should update to the most current stuff?

**Comment by reshnm** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by reshnm** [comment]
@tstuefe @RealCLanger I leave it to you, to squash and merge :-)

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Pull request merged**
