### PR TITLE
Sapmachine (22) #1502: Integrate public changes of OpenJDK 22.0.1

### PR DESCRIPTION
**Pull request by RealCLanger**
Integrate public changes of OpenJDK 22.0.1

fixes #1502

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
Looks good to me.

**Review by MBaesken — APPROVED** [review]

**Pull request merged**
