### PR TITLE
Merge sapmachine11.0.16.1

### LINKED ISSUE #1229: Merge SapMachine 11.0.16.1 and 17.0.4.1
We need to build SapMachine releases 11.0.16.1 and 17.0.4.1

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #1229

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by schmelter-sap — APPROVED** [review]
Looks good.

**Comment by tstuefe** [comment]
This is weird. "Files changed" over all commits does not show me the version change. But the version change commit is in the list of commits...

**Comment by tstuefe** [comment]
I assume you took the version stuff out since you want to keep the version in sapmachine11 branch at 11.0.17,  right?

**Review by tstuefe — APPROVED** [review]
Apart from the missing (?) version number change, this looks ok.

I did a test build from your PR branch and made sure the error is not reproducable. As a comparison, I made a test build from sapmachine11 branch head and there the error was reproducable. So this backout works.

**Comment by RealCLanger** [comment]
> I assume you took the version stuff out since you want to keep the version in sapmachine11 branch at 11.0.17, right?

Yes, the sapmachine-11.0.16.1 tag has already been published here: https://github.com/SAP/SapMachine/releases/tag/sapmachine-11.0.16.1
It is based on sapmachine-11.0.16. The commit that the tag points to (66e710dbc1e4cf8255e97814371ce7a78b5c82e9) is not yet contained in a branch in the repository and the purpose of this PR is to merge it into the sapmachine11 branch.

**Pull request merged**
