### PR TITLE
Merge public changes for SapMachine 16.0.1

### LINKED ISSUE #836: Merge public changes for SapMachine 16.0.1
In https://github.com/openjdk/jdk16u, the last change which went into 16.0.1 is e3e74008e8bbbbad2034931a4a0b5b55099e0138 (https://github.com/openjdk/jdk16u/commit/e3e74008e8bbbbad2034931a4a0b5b55099e0138).
We should merge this into sapmachine16 now for testing and preparing release 16.0.1, along with JDK-8263587

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #836

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
Looks good to me.

**Review by TheRealMDoerr — APPROVED** [review]
Looks good. Thanks for picking up 8263587.

**Pull request merged**
