### PR TITLE
SapMachine #418: Update Problem Lists

### LINKED ISSUE #418: Update Problem Lists
It's time to update the SapMachine problem lists with new contents from our test environment.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #418

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
> vmTestbase/vm/mlvm/cp/stress/classfmt/mt/TestDescription.java generic-ppc64,linux-ppc64le - I think this got an ignore tag anyway , because with the ASM 7.0 update the constpool stressers do not work any more. But it is okay to me to keep the exclusion (maybe with a better comment ?).

Nah, you are right. This exclusion is JDK11 specific. Removing in higher test lists.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
Pushed an updated version...

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by RealCLanger** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Pull request merged**
