### PR TITLE
Prepare SapMachine 20.0.2

### LINKED ISSUE #1428: Prepare SapMachine 20.0.2
Merge public changes for OpenJDK 20.0.2 from [jdk20u](https://github.com/openjdk/jdk20u) to sapmachine20 branch in preparation for the July update.

### PR DESCRIPTION
**Pull request by RealCLanger**
fixes #1428

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by MBaesken — APPROVED** [review]

**Comment by SapMachine** [comment]
Hello @RealCLanger, this pull request fulfills all formal requirements.

**Review by ArnoZeller — APPROVED** [review]
Fine for me - mac and ppcle are known issues.

**Pull request merged**
