### PR TITLE
Sapmachine #1058: Vitals: Integrate March 2022 updates (11)

### LINKED ISSUE #1058: Vitals: Integrate March 2022 updates
Vitals have gotten a number of improvements. Its time to bring those to SapMachine, SAPJVM.

### PR DESCRIPTION
**Pull request by tstuefe**
Backport of https://github.com/SAP/SapMachine/issues/1058 to SapMachine 11.

Mostly unexciting, but I needed to integrate https://github.com/SAP/SapMachine/issues/975 first, which I had not done for 17 and 11. For simplicity, I kept these two in this one PR.

I needed to change the initialization of the pthread-mutex-based Locker class (vitalsLocker.cpp), since in jdk11 we don't support std++11 and therefore cannot use PTHREAD_MUTEX_LIST in member initializer lists (its a compound type at least on glibc).

fixes #1058

### CODE REVIEW

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by tstuefe** [comment]
retest this please

**Comment by SapMachine** [comment]
Hello @tstuefe, this pull request fulfills all formal requirements.

**Comment by tstuefe** [comment]
Test errors seem unrelated, infrastructure problems.

To be sure, I manually built and tested on Linux ppcle and Linux aarch64, as well as minimal build, all went well.

**Review by RealCLanger — APPROVED** [review]
LGTM, test failure on linux ppc64le is unrelated.

**Review by ArnoZeller — APPROVED** [review]
Fine for me. test failure seems to be unrelated.

**Pull request merged**
